### ISSUE TITLE
android-tools in required packages

### ISSUE THREAD

**Issue by steckes** [sameemul-haque/dotfiles#11]
hey, it's a very cool project first of all!
Why are android-tools in the required packages, is it really required?

```bash
pacman -Syu --needed hyprland hyprpaper hypridle waybar sddm hyprlock konsole dunst libnotify fastfetch ttf-firacode-nerd ttf-jetbrains-mono-nerd pamixer bash-completion cliphist slurp grim github-cli libmtp gvfs-mtp android-tools ntfs-3g noto-fonts-emoji
```

**Comment by sameemul-haque** [comment]
Hi, 

[android-tools](https://archlinux.org/packages/extra/x86_64/android-tools/), it's not strictly required for this Hyprland setup. I added it (and some other packages) because I typically use them in my personal workflow and wanted to make sure I don't forget them during future setups. If you don't need `android-tools` or any other packages, feel free to skip them when installing.

Thanks.
