### ISSUE TITLE
Is it possible to revert back

### ISSUE THREAD

**Issue by debanath** [sameemul-haque/dotfiles#6]
I am installing the dotfiles but i also want to know if i'll be able to revert back to the default settings if i want to. If so how. Also a suggestion that it could be helpful if you include some sort of install and uninstall script in the repo that can make things easier for newbies like me.

**Comment by sameemul-haque** [comment]
To help you better, I need a little more information:

1. Are you familiar with Git for managing dotfiles?
2. Have you installed Hyprland + Waybar yet?
3. Have you tried customizing the configuration of Hyprland or Waybar before?

Regarding the install/uninstall script, I'm not planning to add one at the moment. However, since I'm using [Git to manage dotfiles](https://www.atlassian.com/git/tutorials/dotfiles), I’m confident you can easily revert to your previous configuration.

**Comment by debanath** [comment]
1. i am familiar with git but i mostly always used the vs code's gui for version control, i tried to read your blog on how to manage dotfiles but i think i'll have to research a bit more
1. Yes, i have both Hyprland and waybar installed
1. I tried to do a lil bit of customization like wallpaper, some keybinds and a lil bit of the waybar

**Comment by debanath** [comment]
Also i am having issue downloading the sddm-sugar-candy-git
```
$ yay -S --needed sddm-sugar-candy-git
AUR Explicit (1): sddm-sugar-candy-git-r53.2b72ef6-1
:: PKGBUILD up to date, skipping download: sddm-sugar-candy-git
  1 sddm-sugar-candy-git                     (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==>
  1 sddm-sugar-candy-git                     (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==>
==> Making package: sddm-sugar-candy-git r53.2b72ef6-1 (Sun 22 Sep 2024 08:30:33 PM IST)
==> Retrieving sources...
  -> Cloning sugar-candy git repo...
Cloning into bare repository '/home/deba/.cache/yay/sddm-sugar-candy-git/sugar-candy'...
fatal: unable to access 'https://framagit.org/MarianArlt/sddm-sugar-candy.git/': Failed to connect to framagit.org port 443 after 133214 ms: Could not connect to server
==> ERROR: Failure while downloading sugar-candy git repo
    Aborting...
 -> error downloading sources: /home/deba/.cache/yay/sddm-sugar-candy-git
	 context: exit status 1
	

:: (1/1) Parsing SRCINFO: sddm-sugar-candy-git
==> Making package: sddm-sugar-candy-git r53.2b72ef6-1 (Sun 22 Sep 2024 08:32:47 PM IST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Cloning sugar-candy git repo...
Cloning into bare repository '/home/deba/.cache/yay/sddm-sugar-candy-git/sugar-candy'...
fatal: unable to access 'https://framagit.org/MarianArlt/sddm-sugar-candy.git/': Failed to connect to framagit.org port 443 after 133664 ms: Could not connect to server
==> ERROR: Failure while downloading sugar-candy git repo
    Aborting...
 -> error making: sddm-sugar-candy-git-exit status 1
 -> Failed to install the following packages. Manual intervention is required:
sddm-sugar-candy-git - exit status 1
```

do you have any workaround or suggestion on how i can fix it or is it a problem with the package itself

**Comment by sameemul-haque** [comment]
for sddm theme, try this one  [sddm-sugar-candy-git ](https://aur.archlinux.org/packages/sddm-sugar-candy-git)

**Comment by sameemul-haque** [comment]
for sddm theme, try [sddm-theme-sugar-candy-git](https://aur.archlinux.org/packages/sddm-theme-sugar-candy-git) or [sddm-sugar-dark](https://aur.archlinux.org/packages/sddm-sugar-dark)

**Comment by sameemul-haque** [comment]
If you're customizing over my dotfiles, just follow the [installation steps](https://github.com/sameemul-haque/dotfiles?tab=readme-ov-file#installation) and make the changes you need. Afterward, you can use `config diff` to view the changes you’ve made. If you want to save those changes, commit them with `config commit -am 'commit message'`.

To undo all the changes, you can run `config reset --hard`. If you only want to revert specific files, run `config status` to see which files were modified, and you can restore individual files with `config restore file-path-here`.

These are all [Git](https://git-scm.com/) commands. I've mentioned how to set up the `config` alias for managing the dotfiles [in my .bashrc](https://github.com/sameemul-haque/dotfiles/blob/bd2b0a7334bc9267b4dd13335d436f1beff669ad/.bashrc#L1C1)

Also, a suggestion: try using Git in the terminal instead of a GUI for your other projects as well. This will help you better understand the commands and processes involved.

If this clarifies your doubts, you can close the issue. If you need further help, feel free to ask.

**Comment by debanath** [comment]
That you for the suggestion and the help. Yes, i am indeed planning on switching to cli based version control as it will help me understand better whats going on behind the scene and will help me grow further as a dev.
